version: '3.5'

services:
  coredb:
    container_name: coredb
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: coredb
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes: 
      - coredb:/var/lib/postgresql/data
    networks:
      - multiplier

  kafka0:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092"
      - "9093"
      # Map the container's port 9094 to the host machine's port 9094 for external clients to connect
      - "9094:9094"
    volumes:
      - "kafka0-data:/bitnami"
    networks:
      - multiplier
    environment:
      # Show debug logs
      BITNAMI_DEBUG: 1
      # Plaintext listener means the listener is without authentication and non-encrypted. Used for development only.
      ALLOW_PLAINTEXT_LISTENER: "yes"
      # A list of Kafka brokers in a quorum
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka0:9093"
      # Broker ID
      KAFKA_CFG_NODE_ID: 0
      # Cluster ID is created by "kafka-storage random-uuid"
      KAFKA_KRAFT_CLUSTER_ID: "qYoMEZXcS_SKP2PzAl8-WA"
      
      # Bitnami has configured:
      # + "listeners" as "PLAINTEXT://:9092,CONTROLLER://:9093".
      # + "advertised.listeners" as "PLAINTEXT://:9092"
      # See https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#configuration
      # "listeners" is what the broker will use to create server sockets.
      # "advertised.listeners" is what clients will use to connect to the brokers.

      # Override the default configuration values to expose INTERNAL and EXTERNAL listeners.
      # EXTERNAL listener allows external clients like ProductApp to connect.
      # See https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md#accessing-apache-kafka-with-internal-and-external-clients
      KAFKA_CFG_LISTENERS: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka0:9092,EXTERNAL://localhost:9094"

      # Map between listener names and security protocols.
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      # Name of listener used for communication between brokers.
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"

volumes:
  coredb:
  kafka0-data:

networks:
  multiplier:
    driver: bridge
