spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://localhost:5432/coredb
    username: coredb
    password: password
grpc:
  server:
    port: 9091
    security:
      enabled: false
