spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coredb
    username: coredb
    password: password
platform:
  docgen:
    kafka:
      bootstrap-servers: "localhost:9094"
      group-id: company-service
      auto-startup: true
grpc:
  server:
    port: 19091
    security:
      enabled: false
